[general]
import = [
    "tokyonight_night.toml"
]

[window]
padding = { x = 0, y = 0 }
opacity = 0.85
decorations = "none"
startup_mode = "Maximized"

[font]
size = 13.5

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "UbuntuMono Nerd Font Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 0
