unbind r
bind r source-file ~/.tmux.conf

# ` key bound to leader
unbind C-b
set -g prefix `

# Double press to send a ` character
bind-key ` send-prefix

set -g mouse on

set-option -g status-position top

# Vim navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# RGB Color Override
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "joaofelipegalvao/tokyo-night-tmux"

set -g @tokyo-night-tmux_theme night   # night | storm | moon | day
set -g @tokyo-night-tmux_window_id_style hsquare   # window tab numbers
set -g @tokyo-night-tmux_pane_id_style hsquare     # pane number shown in status bar
set -g @tokyo-night-tmux_zoom_id_style qsquare     # pane number shown when zoomed

# # TokyoNight colors for Tmux
# set -g mode-style "fg=#7aa2f7,bg=#3b4261"
# 
# set -g message-style "fg=#7aa2f7,bg=#3b4261"
# set -g message-command-style "fg=#7aa2f7,bg=#3b4261"
# 
# set -g pane-border-style "fg=#3b4261"
# set -g pane-active-border-style "fg=#7aa2f7"
# 
# set -g status "on"
# set -g status-justify "left"
# 
# set -g status-style "fg=#7aa2f7,bg=#16161e"
# 
# set -g status-left-length "100"
# set -g status-right-length "100"
# 
# set -g status-left-style NONE
# set -g status-right-style NONE
# 
# set -g status-left "#[fg=#15161e,bg=#7aa2f7,bold] #S #[fg=#7aa2f7,bg=#16161e,nobold,nounderscore,noitalics]"
# set -g status-right "#[fg=#16161e,bg=#16161e,nobold,nounderscore,noitalics]#[fg=#7aa2f7,bg=#16161e] #{prefix_highlight} #[fg=#3b4261,bg=#16161e,nobold,nounderscore,noitalics]#[fg=#7aa2f7,bg=#3b4261] %Y-%m-%d  %I:%M %p #[fg=#7aa2f7,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#15161e,bg=#7aa2f7,bold] #h "
# if-shell '[ "$(tmux show-option -gqv "clock-mode-style")" == "24" ]' {
#   set -g status-right "#[fg=#16161e,bg=#16161e,nobold,nounderscore,noitalics]#[fg=#7aa2f7,bg=#16161e] #{prefix_highlight} #[fg=#3b4261,bg=#16161e,nobold,nounderscore,noitalics]#[fg=#7aa2f7,bg=#3b4261] %Y-%m-%d  %H:%M #[fg=#7aa2f7,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#15161e,bg=#7aa2f7,bold] #h "
# }
# 
# 
# 
# setw -g window-status-activity-style "underscore,fg=#a9b1d6,bg=#16161e"
# setw -g window-status-separator ""
# setw -g window-status-style "NONE,fg=#a9b1d6,bg=#16161e"
# setw -g window-status-format "#[fg=#16161e,bg=#16161e,nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=#16161e,bg=#16161e,nobold,nounderscore,noitalics]"
# setw -g window-status-current-format "#[fg=#16161e,bg=#3b4261,nobold,nounderscore,noitalics]#[fg=#7aa2f7,bg=#3b4261,bold] #I  #W #F #[fg=#3b4261,bg=#16161e,nobold,nounderscore,noitalics]"
# 
# # tmux-plugins/tmux-prefix-highlight support
# set -g @prefix_highlight_output_prefix "#[fg=#e0af68]#[bg=#16161e]#[fg=#16161e]#[bg=#e0af68]"
# set -g @prefix_highlight_output_suffix ""

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'



if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
